blank_issues_enabled: false
contact_links:
  - name: General question
    url: https://github.com/iLtanaka/RimTouch/issues
    about: For questions, ideas, or discussion that are not clear bug reports.
